AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Lint/BooleanSymbol:
  Exclude:
    - spec/container_config/coercer/symbol_spec.rb
